apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels: { app: test-app }
spec:
  replicas: 1
  selector: { matchLabels: { app: test-app } }
  template:
    metadata: { labels: { app: test-app } }
    spec:
      containers:
      - name: hpa-example
        image: registry.k8s.io/hpa-example
        ports: [ { containerPort: 80 } ]
        resources:
          requests: { cpu: "200m" }
          limits:   { cpu: "500m" }
